---
title: "Today I learned"
date: 2020-02-28T23:29:49+07:00
tag: ["TIL","TodayILearn","todayilearn"]
author: "Kevin Truong"
---

:projectdir: ../../
:imagesdir: ${projectdir}/assets/
:toclevels: 4
:toc:
:toc: left
:sectnums:
:source-highlighter: coderay
:sectnumlevels: 5

== TIL - TODAY I LEARN

I usually read news/articles in HN (hacker news). And really excited and inspired by five-year-and-counting-collection by *Josh Branchaud* on GitHub.
And I also learn from another guy *Simon Willison* about his ideal on using github action with some script to create his own
TIL automatically. Then I asked myself that I do need this also. To track down what I learned day by day and also to keep
the TIL like dictionary for my work.





=== bash 
* link:bash/bash_cheat_sheet[Bash Cheat Sheet] 2020-05-04


=== python 
* link:python/simple_work_flow[Simple Work Flow] 2020-05-07


=== C_Cpp 
* link:c_cpp/embedded-c-object-oriented-programming-part-1[Embedded C - OOP approaching] 2020-05-03
* link:c_cpp/fat_pointer[Fat pointer] 2020-05-07


=== LBI 
* link:lbi/global-static-object-evil[LBIQ- Why static or global object is evil] 2020-05-07
