baseURL = "https://kencancode.xyz"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "KenCanCode.xyz"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
buildExpired = true

[params]
  editURL = "https://github.com/kevintruong/kevin-blogs/edit/master/content/"
  description = "KenCanCode.xyz"
  author = "Kevin Truong"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLanguageSwitchingButton=true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Ideas"
url = "ideas"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30
