################################# Default configuration ###################
# provide your domain here
baseURL = "https://kencancode.xyz"
# theme
theme = "dot"
# site title
title = "Kevin-Truong"
# desable language
disableLanguages = []

############################# Default Parameters ##########################
[author]
    name = "Kevin Truong Cong Hoan Vu"
    alias = "kevin-truong"
    email = "kevin.truong.ds@gmail.com"
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
secondary_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"

# font family
font_family = "Open Sans Condense" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io

############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/Vudevil"

#[[params.social]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#icon = "ti-vimeo-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#link = "#"


################################# navigation ################################
[[menu.main]]
name = "Forex"
url = "forex"
weight = 1

[[menu.main]]
name = "Blogs"
url = "blogs"
weight = 2

# Dropdown menu
[[menu.main]]
weight = 3
name = "docs"
hasChildren = true

  [[menu.main]]
  parent = "docs"
  name = "Blogs"
  url = "blogs"
  weight = 1


  [[menu.main]]
  parent = "docs"
  name = "Travelling"
  url = "Travelling"
  weight = 2

  [[menu.main]]
  parent = "docs"
  name = "Forex"
  url = "forex"
  weight = 2


################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "The Kevin Blogs are copyright © Kevin-Truong 2020."

# banner
[Languages.en.params.banner]
title = "Kevin Truong Knowledge base"
description = "You can find my writing"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
description = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"

