---
title: "KenCanCode.xyz"
---

== KenCanCode

Hello, My name Vu Truong/Kevin Truong this is my blog to describe about my work, my knowledge, and also my note about
what I am doing and also what I learn or experience in the IT industry.

I also have a youtube channel call https://www.youtube.com/channel/UCUI_23Sh86s0PTEiYyHl3lQ[KenCanCode]. The youtube channel will
share your guys some my live coding sessions, and also some tutorials which I found out or relearn from others

== My Projects

* link:projects/easy-framework[Easy Framework]
* link:projects/workspace-rsync[Workspace Rsync]

== Contribute to this documentation
Feel free to update this content, just click the **Edit this page** link displayed on top right of each page, and pullrequest it

{{% notice info %}}
Your modification will be deployed automatically when merged.
{{% /notice %}}

== Donwload all my posts

{{%attachments title="Related files" pattern=".*(pdf|mp4)"/%}}

== Documentation website
This current documentation has been statically generated with Hugo with a simple command : `hugo -t hugo-theme-learn` -- source code is [available here at GitHub](https://github.com/matcornic/hugo-theme-learn)

{{% notice note %}}
Automatically published and hosted thanks to [Netlify](https://www.netlify.com/). Read more about [Automated HUGO deployments with Netlify](https://www.netlify.com/blog/2015/07/30/hosting-hugo-on-netlifyinsanely-fast-deploys/)
{{% /notice %}}