+++
fragment = "content"
weight = 100

title = "DNSMASQ - DHCP extending"

[sidebar]
  sticky = true
+++

:projectdir: ../../
:imagesdir: ${projectdir}/assets/
:source-highlighter: coderay
:sectnumlevels: 5
:sectnums:

[abstract]
.Abstract
DNSMASQ is common software for DNS and DHCP Documentation is a distillation of many long, squiggly adventures.

== A. Feature description

=== 1. DHCP multiple request

By default, DNSMASQ is not designed for process multiple dhcp request in the same time.
With original source, If there have more than 6 DHCP request at the same time.
DHCP will offer the same address from the 6rd

=== 2. DHCP sequential allocation

If DHCP server already allocated a range of IP, for example: from `x.y.10.2` to `x.y.10.30` and then there have manual IP address like `x.y.10.50`.
Then IP address is allocated by DHCP server.
So DHCP sequential will offer from `x.y.10.50` in in stead of `x.y.10.31` as expected.

=== B. Solution approach

==== 1. DHCP multiple request

Whenever DHCP offers IP address, I will store the address to a simple linked list call `offered` list.
Then if DHCP received multiple DHCP request, then It will checked single one by one available IP adddress with out existed in Leases file.

The checking will also double check whether or not the IP address was offered by checking `offered` list. if the current IP address is not in offered list and also avail to allocate -> DHCP server will allocate the IP address to DHCP client.

[.text-center]
.DHCP multiple request origin
[plantuml,dhcp_multiple_request_origin,svg,align="center"]
----
start
:receive_dhcp_discovery();
:max_addr=leases_get_max_addr();
:start = max_addr;
while(!is_ip_addr_valid(start)? &&\n loop_full_range!=true &&\n cached_out!=true)
    :start++;
endwhile
:offer_ip_address(start);
stop
----

[.text-center]
.DHCP multiple request extension handler
[plantuml,dhcp_multiple_request_extension,svg,align="center"]
----
start
:receive_dhcp_discovery();
:max_addr=leases_get_max_addr();

while (check_offered(max_addr)?)
  :max_addr++;
endwhile
:start = max_addr;
while(!is_ip_addr_valid(start)? &&\n loop_full_range!=true &&\n cached_out!=true)
    :start++;
endwhile
:offer_ip_address(start);
:record_offer(start);
stop
----

==== 2. DHCP sequential allocation

===== Problem:

If DHCP server already allocated a range of IP, for example: from `x.y.10.2` to `x.y.10.30` and then there have manual IP address like `x.y.10.50`.
Then IP address is allocated by DHCP server.
So DHCP sequential will offer from `x.y.10.51` in in stead of `x.y.10.31` as expected.

===== Solution:

* Already try a round it when implement DHCP reservation.
Need to rework on how dnsmasq push an entry to its leases list.
By change it from Single Linked List to Sorted Single Linked list.
But the implementation must be more complicate than say.

* The leases sorted single linked list will have multiple segment for IPv4 and IPv6 separately.
For each segment of IPv4 and IPv6, it will contain another child segment for LAN IPv4 and IPv6 subnet.
Just imaging that we have Single Linked will contain a multiple segment for multiple LAN subnet (IPv4 and IPv6) and each segment must be sorted.

First of all, we need to know that at beginning, dnsmasq using leases file as database to store all lease entry.
But it just push the new entry to the end of leases file (single linked list).
To archive DHCP sequential without break the rule (Dnsmasq using leases file as global variable and it is used alot in the application) we need to leverage the current leases file.

[.text-center]
.leases file - simple single linked content lease entry
[plantuml,dhcp_sequential_flow_chart,svg]
----
leases -down->subnet_1_ipv4_addr1
-right-> subnet_1_ipv4_addr2
-right-> subnet_2_ipv4_addr1
-right-> subnet_1_ipv6_addr1
-down-> subnet2_ipv4_addr2
-left->subnet1_ipv4_addr3
----

[.text-center]
.Leases file single linked contain sorted subnet
[plantuml,dhcp_sequential_flow_chart_extension,svg,align="center"]
----
leases -down->sorted_subnet_1_ipv4
-right-> sorted_subnet_2_ipv4
-right-> sorted_subnet_3_ipv4
-right-> all_subnet_ipv6
note right: call each sorted subnet/subnet is segment
----

dhcp will using function lease_get_max_addr to get the current max ip address stored in lease file.
the max_addr return will using as a seeding number. and then start from the seeding number , the dnsmasq will check which is address is available by increament the seeding addr.
For example: We have network address 192.168.0.0/24 and already allocated IP address (manually by DHCPRequest): 192.168.0.100 the leases_get_max_addr() will return the max_addr now is 192.168.0.100. Then dnsmasq will start to check from `.0.100`
then it will check the next is `.0.101` naturally.
So, it is not expected as we enable sequential IP allocate.

[.text-center]
.Origin implement of leases_get_max_addr() of dnsmasq
[plantuml,dhcp_sequential_flow_chart_origin_activity,svg,align="center"]
----
start
:receive_dhcp_discovery();

:max_addr=leases_get_max_addr();
partition leases_get_max_addr() #LightSkyBlue {
:max_lease=leases;
note right: Detail implement of leases_get_max_addr() start
:cur_lease=leases;
while (cur_lease)
  if (in_range(context,cur_lease)?)
     if ((cur_lease->addr > max_lease->addr)?)
        :max_lease = cur_leases;
     endif
  endif
  :cur_lease=cur_lease->next;
endwhile
:max_addr = max_lease->addr;
note right: Detail implement of leases_get_max_addr() end
}
:start = max_addr;
while(!is_ip_addr_valid(start)? &&\n loop_full_range!=true &&\n cached_out!=true)
    :start++;
endwhile
:offer_ip_address(start);
:record_offer(start);
stop

----

[.text-center]
.New implement for sequential dnsmasq
[plantuml,dhcp_sequential_flow_chart_extension_activity,svg,align="center"]
----
:cur_segment=find_segment(context);
:cur_lease=cur_segment;
:max_lease=cur_segment;
while (cur_lease)
  if (in_range(context,cur_lease)?)
     if ((cur_lease->addr > max_lease->addr)?)
        if (cur_lease->next != cur_lease->addr +1 ?)
            break
        endif
        :max_lease = cur_leases;
     endif
  else
    break
  endif
  :cur_lease=cur_lease->next;
endwhile
:max_addr = max_lease->addr;
----

by this algorithm , we can find out which address in sequential is missing.
For example: we have `.2,.3,.4,.5,.10`
we will find now the maximum return with new implement is `.5` . Then dnsmasq will check and allocate from .5
