---
title: "Embedded C - OOP approaching"
date: 2020-02-28T23:29:49+07:00
draft: true
tag: []
author: "Kevin Truong"
---

:projectdir: ../../
:imagesdir: ${projectdir}/assets/
:source-highlighter: coderay
:sectnumlevels: 5
:sectnums:

== EMBEDDED C - Object Oriented Programming Approaching

<<<
:toc: left
<<<

<<<

*HISTORY*

[cols="1,1,1,3",options="header",]
|===============================================================================================
|Version |Date |Author |Remark
|0.1 |March 19, 2020 |Vu Truong |First created
|===============================================================================================

<<<

```
No programming technique solves all problems.
No programming language produces only correct results.
No programmer should start each project from scratch
```

=== Encapsulated

```
Encapsulation is the mechanism of hiding of data implementation by restricting access to public methods. Instance variables are kept private and accessor methods are made public to achieve this.
```

In ANSI C, to archive the attribution then we need to understand about `.c` and `.h` files to me, the `.h` file is where we will describe about which is `interface` , the other `.c` will be where we define about `implementation`.
We have two new concepts `interface` and `implementation`.
By understanding the `interface` and `implementation` in C, then we can archive encapsulate attribution of C.

==== Interface in C

We develop a module call A, then Can understand Interface of A (`A_Intf`) in practically is something we want expose to the world A will expose some functionality which it can like Do_X, Do_Y by interface API like
`A_Do_X`, `A_Do_Y`

For example: module B can require A for some durty work by used its interface API by calling `A_Do_X`
The interface will describe in `A.h` , the implementation of the interface will push in `A.c`.
But it is just implementation of interface We need another `.c` file to hold detail impelement of module.
In the case, I will use file `A_Impl.c`
so, for a module A:

```
A.h   \\ Interface declare
A.c   \\ Interface implementation
A_Impl.c  \\ Detail implementation of module A
```

But this way for some verify complex module when module A will have many ways for implementation bufor example: A need to support `unix`, support `OS_X` , support `Win32` ... then the detail implementation for the module is need to extend

```
A.h   \\ Interface declare
A.c   \\ Interface implementation
A_Impl_Unix.c  \\ Detail implementation of module A in Unix platform.
A_Impl_OSX.c  \\ Detail implementation of module A in OSX platform.
A_Impl_Win32.c  \\ Detail implementation of module A in WIN32 platform.
```

the `A.c` will on/off code blocks which is compiled based on platform variable.

Another example is module A has two ways implementation for two algorithms call `alpha` and `omega`.
The module A

the thumb rule here is: When we make a new module, We must careful on consider what is interface of module, what we need to expose to the world ?

==== implementation in C

According to above session, we can simply understand the implementation in C practically that It includes implementation of interface and detail implementation of module.

So, we push all implementation of module in `.c` files.
We must think that Users who used the module, will be limited to access the module.
They only know about the module through the module interface.
And also, they don't care about how it is implemented.
They only care about its functionality and how well it works.

For example: Like above section, Module A only provided 2 API (interface) cal A_Do_X and A_Do_Y. the detail implement of
`A_Do_X` and `A_Do_Y` in Unix platfrom will be A_Do_X_Unix_Impl and `A_Do_Y_Unix_Impl` , also `A_Do_X_OSX_Impl` and
`A_Do_Y_OSX_Impl` for OSX is quite complex.
Maybe 2000 or 3000 lines of code with combined of multiple static function.
But as an User, to use the module, I don't care about its implementation.
I care about how simple to use the API (interface) of module and how good the lib work.
With the simple interface declare, A_Do_X and A_Do_Y then the user don't take much effort to use the module.
Just `A_Do_X` and `A_Do_Y`.
And the magic come.

[]
.A.h
[source,c]
----
#ifndef _A_H_
#define _A_H_

void A_Do_X();
void A_Do_Y();

#endif
----

[]
.A.c
[source,c]
----
#include "A.h"
#include "A_Imple.h"

void A_Do_X(){
    return A_Do_X_Impl();
}

void A_Do_X(){
    return A_Do_Y_Impl();
}

----

[]
.A_Impl.h
[source,c]
----
void A_Do_X_Impl();

void A_Do_Y_Impl();

----

[]
.A_OSX_Impl.c
[source,c]
----
#include "A_Imple.h"

void A_Do_X_Impl(){
    // detail implement of Do_X in OSX platform
}

void A_Do_Y_Impl(){
    // detail implement of Do_X in OSX platform
}

----
[]
.A_Unix_Impl.c
[source,c]
----
#include "A_Imple.h"

void A_Do_X_Impl(){
    // detail implement of Do_X in OSX platform
}

void A_Do_Y_Impl(){
    // detail implement of Do_X in OSX platform
}

----

=== Abstraction

```
Abstract means a concept or an Idea which is not associated with any particular instance.
```
In C, I like the pointer concept. A void pointer can point to any data type. In another word, a void pointer
can be any data type. From an array to specticular structure.

For example:
[]
.Void pointer point to an array
[source,c]
----
void *pArray = NULL;
char sHelloWorld[] = "Hello World"
pArray = sHelloWorld;
printf("str from Array: %s",sHelloWorld);
printf("str from pointer: %s",pArray);
----

=== Inheritance

```
Inheritances expresses “is-a” and/or “has-a” relationship between two objects.
```
