---
title: "WordPress SQL Cloud and Cloud Run GithubAction Make Your WordPress Simple"
date: 2020-04-15T12:21:58Z
draft: true
---

:projectdir: ../../
:imagesdir: ${projectdir}/assets/
:toclevels: 4
:toc:
:sectnums:
:source-highlighter: coderay
:sectnumlevels: 5

== WordPress SQL Cloud and Cloud Run GithubAction Make Your WordPress Simple
So, My wife need a website , kind of portfolio website to present all design project which she already done. I already
told him about HUGO + Asciidoc + Hugo theme to make simple static web. But look like she fall in love with WordPress. OK,
I still fine. But I do not like WordPress so much. Because the progress to deploy a website in WordPress is annoying me.
To deploy a website in Wordpress need many steps like bellow:

1. Register a domain like www.example.com
2. Register Hosting and access to Hosting to install WordPress
3. Intialize WordPress, theme design , setup WordPress site as your purpose
4. Mapping Domain name with your Hosting

Basically, we will have 4 steps like this. But the annoying here is step 2 and 3.
The inital WordPress with non-tech guy even you are an enginer but not Web Enginer then you will struggle on some thing like
how to ssh to remote server, how do mapping Domain Name with your hosting public IPv6/IPv6. After that we will facing with the
real monster here : Configure your WordPress after it online. Because of design work load. You have to upload image, design theme and
re-arrange all elements for simple but beauty website. But your hosting is not quite fast, you upload some iamges and need to F5 to check
wheter or not it is corrects. So, I think we will need a faster , simple process here.

=== Solution
- For cheap hosting: I used Google Cloud Run to run WordPress. You can find out WordPress Google Cloud Run. With few clicks we already have WordPress
Cloud Run.
- For DB will make Cloud SQL with minimal require for lowest costing as posible
- For automate deploy I use github action to CI/CD my wife's website.

=== Modeling

[.text-center]
.Cloud Run - Cloud SQL - WordPress - Github Action
[plantuml,CI_CD_WordPress,svg,align="center"]
----
package "Cloud Run" {
  HTTP - [WordPress]
  [Theme]
}

node "Cloud SQL" {
  TCP - [DB]
  [WordPress] --> TCP
}

node "Github" {
    [WordPressRepo] --> [GithubAction]
    [GithubAction] --> [Theme]
    [GithubAction] --> [WordPress]
}

node "Local" {
    [Local DB] <--> [DB]: sync
    [Local WordPress] -> [WordPressRepo]
    [Local Theme] --> [WordPressRepo]
}
User --> HTTP
----

=== Overview

=== How it works

=== Conclusion