---
title: "CV - VU TRUONG CONG HOAN"
date: 2020-05-16T15:45:18Z
draft: true
weight: 500
---

:projectdir: ../../
:imagesdir: ${projectdir}/assets/
:assetsdir: ${projectdir}/static/assets/
:sectnums:
:source-highlighter: coderay
:sectnumlevels: 5

== Employment History

VERIK SYSTEMS - Senior Systems Engineer #June 2019 - Present#::

RAVEN TEAM - Team Leader #Sep. 2018 - June 2019#::

ELINKGATE - Senior Systems Engineer #Jan.2015 - Jan.2019#::

STYL - Embedded Engineer #Oct.2012 - May.2014#::
TODO

== Projects

* Easy Framework: Simple framework for development an application in embedded system
* Workspace-rsync: Simple utility tools to sync up local workspace and remote workspace
* UEFI 21 days training: Training course for getting start with UEFI Application/Driver development
* https://kencancode.xyz[] blogs: Static web blogs for sharing knowledge and promote

== Skills:

- Platform development
- Project/Product management
- Git, Ruby, Bash, Python, AsciiDoc,
- Software development skills set includes: UML, documentation, software architecture, software design.

== Experience:

- 8 years in software development
- 3 years join a startup as co-founder (ELINKGATE)
- 3 years at team lead rule.
Motivate and train team members to better.
- Solutions-oriented technical, structural, and PR problem solving on a client-by-client basis
- Documentation

== Achievements:

- Success on design and implement a VNC Server UEFI driver which allow to remote control Pre-Boot session on PC
- Create render engine based on FFMPEG for batching process video
- Design and structure DevOps for firmware team in VERIK
- Publish many blogs on personal website kencancode.xyz for share experience and knowledge

== contact:

email: kevin.truong.ds@gmail.com

phone: 315-254-0342

web: https://kencancode.xyz

github: https://github.com/kevintruong

